### ISSUE TITLE
Doesn't work in IE11 because of debug-dependency

### ISSUE THREAD

**Issue by reindernijhoff** [larsvanbraam/task-loader#3]
Doesn't work in IE11 because of debug-dependency

**Comment by reindernijhoff** [comment]
grapje, moest even verwijderen en weer opnieuw toevoegen en alles kwam goed!

**Comment by larsvanbraam** [comment]
I changed the debug dependency because the one used was es6 and was not compiled by webpack for some reason. Latest version should be fine! :)
